CREATE TABLE IF NOT EXISTS students_db (
    student_id INT AUTO_INCREMENT PRIMARY KEY,
    student_name VARCHAR(255) NOT NULL,
    curriculum VARCHAR(100) NOT NULL,
    classification VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    programs VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 